ALTER TABLE configuracoes
  ADD COLUMN IF NOT EXISTS advogado_nome text,
  ADD COLUMN IF NOT EXISTS advogado_email text,
  ADD COLUMN IF NOT EXISTS advogado_telefone text,
  ADD COLUMN IF NOT EXISTS advogado_cpf text,
  ADD COLUMN IF NOT EXISTS advogado_foto_url text,
  ADD COLUMN IF NOT EXISTS oab_numero text,
  ADD COLUMN IF NOT EXISTS oab_estado text,
  ADD COLUMN IF NOT EXISTS oab_tipo text DEFAULT 'advogado',
  ADD COLUMN IF NOT EXISTS oab_situacao text DEFAULT 'ativo',
  ADD COLUMN IF NOT EXISTS escritorio_nome text,
  ADD COLUMN IF NOT EXISTS escritorio_cnpj text,
  ADD COLUMN IF NOT EXISTS escritorio_endereco text,
  ADD COLUMN IF NOT EXISTS escritorio_cidade text,
  ADD COLUMN IF NOT EXISTS escritorio_estado text,
  ADD COLUMN IF NOT EXISTS escritorio_cep text,
  ADD COLUMN IF NOT EXISTS escritorio_telefone text,
  ADD COLUMN IF NOT EXISTS escritorio_email text,
  ADD COLUMN IF NOT EXISTS escritorio_logo_url text,
  ADD COLUMN IF NOT EXISTS assinatura_texto text,
  ADD COLUMN IF NOT EXISTS assinatura_rodape text;
